version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
  build:
    commands:
      - echo Build started on `date`
      - next build
  post_build:
    commands:
      - echo Build completed on `date`
      - next start
artifacts:
    files: imagedefinitions.json