version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - npm i -g next
      - npm install --save init -y
      - npm install --save react react-dom next
      - npm install yarn -g
      - yarn add --dev typescript @types/react
  build:
    commands:
      - echo Build started on `date`
      - yarn build
  post_build:
    commands:
      - echo Build completed on `date`